import { PropertyQueryResult } from "@/lib/sanity/types";

// Dummy agent data
const dummyAgents = [
  {
    _id: "agent-1",
    _type: "agent" as const,
    name: "Maria Spasic",
    role: "Senior Real Estate Agent",
    rating: 4.9,
    sold: 127,
    phone: "+30 210 123 4567",
    email: "maria@spasicrealestate.com",
    avatar: {
      _type: "image" as const,
      asset: {
        _ref: "avatar-maria",
        _type: "reference" as const,
      },
      alt: "Maria Spasic profile photo",
    },
    bio: "Specializing in luxury properties across Athens and Greek islands with over 10 years of experience.",
    specializations: ["Luxury Properties", "Waterfront Homes", "Investment Properties"],
    languages: ["English", "Greek", "German"],
  },
  {
    _id: "agent-2",
    _type: "agent" as const,
    name: "Dimitris Kostas",
    role: "Commercial Property Specialist",
    rating: 4.8,
    sold: 89,
    phone: "+30 210 234 5678",
    email: "dimitris@spasicrealestate.com",
    avatar: {
      _type: "image" as const,
      asset: {
        _ref: "avatar-dimitris",
        _type: "reference" as const,
      },
      alt: "Dimitris Kostas profile photo",
    },
    bio: "Expert in commercial real estate and business property investments throughout Greece.",
    specializations: ["Commercial Properties", "Office Spaces", "Retail Locations"],
    languages: ["English", "Greek", "Italian"],
  },
  {
    _id: "agent-3",
    _type: "agent" as const,
    name: "Elena Papadopoulos",
    role: "Residential Property Expert",
    rating: 4.9,
    sold: 156,
    phone: "+30 210 345 6789",
    email: "elena@spasicrealestate.com",
    avatar: {
      _type: "image" as const,
      asset: {
        _ref: "avatar-elena",
        _type: "reference" as const,
      },
      alt: "Elena Papadopoulos profile photo",
    },
    bio: "Passionate about helping families find their perfect home in Greece's most desirable neighborhoods.",
    specializations: ["Family Homes", "First-Time Buyers", "Relocation Services"],
    languages: ["English", "Greek", "French", "Spanish"],
  },
];

// Dummy property data that matches PropertyQueryResult structure
export const dummyProperties: PropertyQueryResult[] = [
  // CONDOS
  {
    _id: "property-condo-1",
    _type: "property",
    title: "Luxury Seafront Condo in Glyfada",
    slug: { current: "luxury-seafront-condo-glyfada" },
    price: 850000,
    currency: "EUR",
    beds: 3,
    baths: 2,
    sqft: 1200,
    propertyType: "Condo",
    status: "For Sale",
    featured: true,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "condo-glyfada-main",
        _type: "reference",
      },
      alt: "Modern seafront condo with ocean views",
    },
    address: {
      street: "Poseidonos Avenue 45",
      city: "Glyfada",
      region: "Attica",
      country: "Greece",
      postalCode: "16675",
    },
    latitude: 37.8642,
    longitude: 23.7578,
    description:
      "Stunning modern condo with panoramic sea views, premium finishes, and private balcony.",
    features: ["Sea View", "Balcony", "Modern Kitchen", "Air Conditioning", "Parking"],
    amenities: ["Swimming Pool", "Gym", "24/7 Security", "Concierge"],
    yearBuilt: 2020,
    lotSize: 0,
    agent: dummyAgents[0],
    publishedAt: "2024-01-15T10:00:00Z",
    _createdAt: "2024-01-15T10:00:00Z",
    _updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    _id: "property-condo-2",
    _type: "property",
    title: "Modern Penthouse in Kolonaki",
    slug: { current: "modern-penthouse-kolonaki" },
    price: 1200000,
    currency: "EUR",
    beds: 4,
    baths: 3,
    sqft: 1800,
    propertyType: "Condo",
    status: "For Sale",
    featured: true,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "penthouse-kolonaki-main",
        _type: "reference",
      },
      alt: "Elegant penthouse with city views",
    },
    address: {
      street: "Voukourestiou 12",
      city: "Athens",
      region: "Attica",
      country: "Greece",
      postalCode: "10671",
    },
    latitude: 37.9755,
    longitude: 23.7348,
    description:
      "Exclusive penthouse in prestigious Kolonaki with rooftop terrace and Acropolis views.",
    features: ["Acropolis View", "Rooftop Terrace", "Fireplace", "Walk-in Closet", "Smart Home"],
    amenities: ["Elevator", "Storage Room", "Parking", "24/7 Security"],
    yearBuilt: 2019,
    lotSize: 0,
    agent: dummyAgents[0],
    publishedAt: "2024-01-20T14:30:00Z",
    _createdAt: "2024-01-20T14:30:00Z",
    _updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    _id: "property-condo-3",
    _type: "property",
    title: "Beachfront Apartment in Mykonos",
    slug: { current: "beachfront-apartment-mykonos" },
    price: 650000,
    currency: "EUR",
    beds: 2,
    baths: 2,
    sqft: 950,
    propertyType: "Condo",
    status: "For Rent",
    featured: false,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "apartment-mykonos-main",
        _type: "reference",
      },
      alt: "Cycladic style beachfront apartment",
    },
    address: {
      street: "Ornos Beach Road",
      city: "Mykonos",
      region: "South Aegean",
      country: "Greece",
      postalCode: "84600",
    },
    latitude: 37.4236,
    longitude: 25.3421,
    description:
      "Traditional Cycladic apartment steps from Ornos Beach with authentic island charm.",
    features: ["Beach Access", "Traditional Architecture", "Furnished", "WiFi", "Garden View"],
    amenities: ["Beach Club Access", "Cleaning Service", "Tourist Support"],
    yearBuilt: 2015,
    lotSize: 0,
    agent: dummyAgents[2],
    publishedAt: "2024-02-01T09:15:00Z",
    _createdAt: "2024-02-01T09:15:00Z",
    _updatedAt: "2024-02-01T09:15:00Z",
  },

  // HOUSES
  {
    _id: "property-house-1",
    _type: "property",
    title: "Traditional Villa in Santorini",
    slug: { current: "traditional-villa-santorini" },
    price: 1850000,
    currency: "EUR",
    beds: 5,
    baths: 4,
    sqft: 2800,
    propertyType: "House",
    status: "For Sale",
    featured: true,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "villa-santorini-main",
        _type: "reference",
      },
      alt: "Traditional Santorini villa with caldera views",
    },
    address: {
      street: "Caldera Cliff Road",
      city: "Oia",
      region: "South Aegean",
      country: "Greece",
      postalCode: "84702",
    },
    latitude: 36.4618,
    longitude: 25.3753,
    description:
      "Breathtaking traditional villa with infinity pool and unobstructed caldera sunset views.",
    features: ["Caldera View", "Infinity Pool", "Cave Rooms", "Sunset Terrace", "Wine Cellar"],
    amenities: ["Private Pool", "Outdoor Kitchen", "Guest House", "Concierge Service"],
    yearBuilt: 2010,
    lotSize: 3500,
    agent: dummyAgents[0],
    publishedAt: "2024-01-10T16:45:00Z",
    _createdAt: "2024-01-10T16:45:00Z",
    _updatedAt: "2024-01-10T16:45:00Z",
  },
  {
    _id: "property-house-2",
    _type: "property",
    title: "Modern Family Home in Kifisia",
    slug: { current: "modern-family-home-kifisia" },
    price: 780000,
    currency: "EUR",
    beds: 4,
    baths: 3,
    sqft: 2200,
    propertyType: "House",
    status: "For Sale",
    featured: false,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "house-kifisia-main",
        _type: "reference",
      },
      alt: "Contemporary family home with garden",
    },
    address: {
      street: "Dionysou 23",
      city: "Kifisia",
      region: "Attica",
      country: "Greece",
      postalCode: "14562",
    },
    latitude: 38.0742,
    longitude: 23.8103,
    description:
      "Contemporary family home in prestigious Kifisia with private garden and modern amenities.",
    features: ["Private Garden", "Modern Design", "Energy Efficient", "Parking", "Security System"],
    amenities: ["Garden", "BBQ Area", "Storage", "Garage"],
    yearBuilt: 2018,
    lotSize: 800,
    agent: dummyAgents[2],
    publishedAt: "2024-01-25T11:20:00Z",
    _createdAt: "2024-01-25T11:20:00Z",
    _updatedAt: "2024-01-25T11:20:00Z",
  },
  {
    _id: "property-house-3",
    _type: "property",
    title: "Seaside Villa in Porto Heli",
    slug: { current: "seaside-villa-porto-heli" },
    price: 1350000,
    currency: "EUR",
    beds: 6,
    baths: 5,
    sqft: 3200,
    propertyType: "House",
    status: "For Sale",
    featured: true,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "villa-porto-heli-main",
        _type: "reference",
      },
      alt: "Luxury seaside villa with private beach",
    },
    address: {
      street: "Coastal Road 15",
      city: "Porto Heli",
      region: "Peloponnese",
      country: "Greece",
      postalCode: "21061",
    },
    latitude: 37.2975,
    longitude: 23.1478,
    description:
      "Exclusive seaside villa with private beach access, guest houses, and luxury amenities.",
    features: ["Private Beach", "Guest Houses", "Boat Dock", "Wine Cellar", "Home Theater"],
    amenities: ["Private Beach", "Boat Dock", "Staff Quarters", "Helipad"],
    yearBuilt: 2017,
    lotSize: 5000,
    agent: dummyAgents[0],
    publishedAt: "2024-02-05T13:00:00Z",
    _createdAt: "2024-02-05T13:00:00Z",
    _updatedAt: "2024-02-05T13:00:00Z",
  },

  // COMMERCIAL PROPERTIES
  {
    _id: "property-commercial-1",
    _type: "property",
    title: "Prime Office Building in Syntagma",
    slug: { current: "prime-office-building-syntagma" },
    price: 3200000,
    currency: "EUR",
    beds: 0,
    baths: 8,
    sqft: 4500,
    propertyType: "Commercial",
    status: "For Sale",
    featured: true,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "office-syntagma-main",
        _type: "reference",
      },
      alt: "Modern office building in central Athens",
    },
    address: {
      street: "Stadiou 10",
      city: "Athens",
      region: "Attica",
      country: "Greece",
      postalCode: "10564",
    },
    latitude: 37.9742,
    longitude: 23.7348,
    description:
      "Premium office building in the heart of Athens financial district with modern facilities.",
    features: ["Central Location", "Modern Elevators", "HVAC System", "Fiber Optic", "Parking"],
    amenities: ["Reception", "Conference Rooms", "Cafeteria", "Parking Garage", "24/7 Security"],
    yearBuilt: 2016,
    lotSize: 0,
    agent: dummyAgents[1],
    publishedAt: "2024-01-18T08:30:00Z",
    _createdAt: "2024-01-18T08:30:00Z",
    _updatedAt: "2024-01-18T08:30:00Z",
  },
  {
    _id: "property-commercial-2",
    _type: "property",
    title: "Retail Space in Ermou Street",
    slug: { current: "retail-space-ermou-street" },
    price: 450000,
    currency: "EUR",
    beds: 0,
    baths: 2,
    sqft: 800,
    propertyType: "Commercial",
    status: "For Rent",
    featured: false,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "retail-ermou-main",
        _type: "reference",
      },
      alt: "Ground floor retail space on busy shopping street",
    },
    address: {
      street: "Ermou 45",
      city: "Athens",
      region: "Attica",
      country: "Greece",
      postalCode: "10563",
    },
    latitude: 37.9755,
    longitude: 23.7268,
    description:
      "High-traffic retail space on Athens' premier shopping street, perfect for flagship stores.",
    features: ["Ground Floor", "Large Windows", "High Ceilings", "Storage Space", "Loading Access"],
    amenities: ["Prime Location", "High Foot Traffic", "Public Transport Access"],
    yearBuilt: 1980,
    lotSize: 0,
    agent: dummyAgents[1],
    publishedAt: "2024-02-10T10:45:00Z",
    _createdAt: "2024-02-10T10:45:00Z",
    _updatedAt: "2024-02-10T10:45:00Z",
  },
  {
    _id: "property-commercial-3",
    _type: "property",
    title: "Industrial Warehouse in Piraeus",
    slug: { current: "industrial-warehouse-piraeus" },
    price: 1800000,
    currency: "EUR",
    beds: 0,
    baths: 4,
    sqft: 8000,
    propertyType: "Commercial",
    status: "For Sale",
    featured: false,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "warehouse-piraeus-main",
        _type: "reference",
      },
      alt: "Large industrial warehouse with loading docks",
    },
    address: {
      street: "Industrial Zone 12",
      city: "Piraeus",
      region: "Attica",
      country: "Greece",
      postalCode: "18545",
    },
    latitude: 37.9364,
    longitude: 23.6478,
    description:
      "Large industrial warehouse with excellent logistics access near Greece's main port.",
    features: ["Loading Docks", "High Ceilings", "Office Space", "Parking", "Security"],
    amenities: ["Port Access", "Highway Connection", "Rail Access", "Security System"],
    yearBuilt: 2005,
    lotSize: 12000,
    agent: dummyAgents[1],
    publishedAt: "2024-01-30T15:15:00Z",
    _createdAt: "2024-01-30T15:15:00Z",
    _updatedAt: "2024-01-30T15:15:00Z",
  },

  // RENTAL PROPERTIES
  {
    _id: "property-rent-1",
    _type: "property",
    title: "Furnished Apartment in Exarchia",
    slug: { current: "furnished-apartment-exarchia" },
    price: 1200,
    currency: "EUR",
    beds: 2,
    baths: 1,
    sqft: 750,
    propertyType: "Apartment",
    status: "For Rent",
    featured: true,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "apartment-exarchia-main",
        _type: "reference",
      },
      alt: "Cozy furnished apartment in artistic neighborhood",
    },
    address: {
      street: "Themistokleous 56",
      city: "Athens",
      region: "Attica",
      country: "Greece",
      postalCode: "10683",
    },
    latitude: 37.9896,
    longitude: 23.7336,
    description:
      "Charming furnished apartment in vibrant Exarchia, perfect for students and young professionals.",
    features: ["Fully Furnished", "Balcony", "WiFi Included", "Near Metro", "Pet Friendly"],
    amenities: ["Central Heating", "Washing Machine", "Kitchen Appliances"],
    yearBuilt: 1965,
    lotSize: 0,
    agent: dummyAgents[2],
    publishedAt: "2024-02-12T12:00:00Z",
    _createdAt: "2024-02-12T12:00:00Z",
    _updatedAt: "2024-02-12T12:00:00Z",
  },
  {
    _id: "property-rent-2",
    _type: "property",
    title: "Luxury Penthouse Rental in Glyfada",
    slug: { current: "luxury-penthouse-rental-glyfada" },
    price: 3500,
    currency: "EUR",
    beds: 3,
    baths: 3,
    sqft: 1600,
    propertyType: "Apartment",
    status: "For Rent",
    featured: true,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "penthouse-glyfada-rental-main",
        _type: "reference",
      },
      alt: "Luxury penthouse with sea views for rent",
    },
    address: {
      street: "Leoforos Vouliagmenis 234",
      city: "Glyfada",
      region: "Attica",
      country: "Greece",
      postalCode: "16675",
    },
    latitude: 37.8708,
    longitude: 23.7567,
    description: "Stunning luxury penthouse rental with panoramic sea views and premium amenities.",
    features: ["Sea View", "Rooftop Pool", "Fully Furnished", "Maid Service", "Concierge"],
    amenities: ["Swimming Pool", "Gym", "Parking", "24/7 Security", "Beach Access"],
    yearBuilt: 2021,
    lotSize: 0,
    agent: dummyAgents[0],
    publishedAt: "2024-02-08T14:20:00Z",
    _createdAt: "2024-02-08T14:20:00Z",
    _updatedAt: "2024-02-08T14:20:00Z",
  },
  {
    _id: "property-rent-3",
    _type: "property",
    title: "Student Housing in Zografou",
    slug: { current: "student-housing-zografou" },
    price: 450,
    currency: "EUR",
    beds: 1,
    baths: 1,
    sqft: 350,
    propertyType: "Apartment",
    status: "For Rent",
    featured: false,
    images: [],
    mainImage: {
      _type: "image",
      asset: {
        _ref: "student-zografou-main",
        _type: "reference",
      },
      alt: "Affordable student apartment near university",
    },
    address: {
      street: "Navarinou 12",
      city: "Athens",
      region: "Attica",
      country: "Greece",
      postalCode: "15773",
    },
    latitude: 37.9687,
    longitude: 23.7712,
    description:
      "Affordable student accommodation near University Campus with all essential amenities.",
    features: ["Student Friendly", "Near University", "WiFi", "Study Area", "Shared Kitchen"],
    amenities: ["Laundry Facilities", "Study Room", "Common Area", "Bike Storage"],
    yearBuilt: 1985,
    lotSize: 0,
    agent: dummyAgents[2],
    publishedAt: "2024-02-15T09:30:00Z",
    _createdAt: "2024-02-15T09:30:00Z",
    _updatedAt: "2024-02-15T09:30:00Z",
  },
];

// Helper functions to filter properties by type
export const getCondoProperties = () => dummyProperties.filter((p) => p.propertyType === "Condo");

export const getHouseProperties = () => dummyProperties.filter((p) => p.propertyType === "House");

export const getCommercialProperties = () =>
  dummyProperties.filter((p) => p.propertyType === "Commercial");

export const getRentalProperties = () => dummyProperties.filter((p) => p.status === "For Rent");

export const getFeaturedProperties = () => dummyProperties.filter((p) => p.featured === true);

// Get random properties (useful for "you might also like" sections)
export const getRandomProperties = (count: number = 6, excludeId?: string) => {
  const filtered = excludeId ? dummyProperties.filter((p) => p._id !== excludeId) : dummyProperties;

  return filtered.sort(() => Math.random() - 0.5).slice(0, count);
};
