import type { Metadata } from "next";
import { Playfair_Display, Montserrat, Inter } from "next/font/google";
import "./globals.css";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import { AppPreferencesProvider } from "@/lib/prefs-context";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import VisualEditsWrapper from "@/visual-edits/VisualEditsWrapper";
import "leaflet/dist/leaflet.css";

const montserrat = Montserrat({
  subsets: ["latin", "greek", "cyrillic", "cyrillic-ext"],
  variable: "--font-montserrat",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const playfair_display = Playfair_Display({
  subsets: ["latin", "cyrillic", "cyrillic-ext"],
  weight: ["400", "700"],
  variable: "--font-playfair-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Spasić Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`text-[#0e100f] ${montserrat.className} ${playfair_display.variable}`}>
      <body className="antialiased">
        <AppPreferencesProvider initialCurrency="eur" initialLanguage="en">
          <div className="min-h-dvh bg-background text-foreground">
            <Header initialCurrency="eur" initialLanguage="en" />

            <main className="w-full">{children}</main>

            <Footer className="border-t bg-background mt-0" />
          </div>

          <ErrorReporter />
          <Script
            src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
            strategy="afterInteractive"
            data-target-origin="*"
            data-message-type="ROUTE_CHANGE"
            data-include-search-params="true"
            data-only-in-iframe="true"
            data-debug="true"
            data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
          />
          <VisualEditsWrapper />
        </AppPreferencesProvider>
      </body>
    </html>
  );
}
